routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::group(["middleware" => "auth"],function(){
    Route::resource('posts', 'PostController');
    Route::group(['middleware' => 'can:superadmin'], function () {
        Route::get('roles','RoleController@roles')->name('roles');
        Route::get('change-permissions/{role}','RoleController@changePermission')->name('change-permission');
        Route::put('update-permissions/{role}','RoleController@updatePermission')->name('update-permission');
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">New Posts</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sidebar.blade.php
<div class="col-md-3">
    <div class="card">
        <div class="card-header">Menu</div>

        <div class="card-body">
            <ul>
                <li>
                    <a href="#">Posts</a>
                    <ul>
                        @if(Auth::user()->hasPermission('add_post'))
                        <li><a href="{{route('posts.create')}}">Create Post</a></li>
                        @endif
                        <li><a href="{{route('posts.index')}}">Post Lists</a></li>
                    </ul>
                </li>
                @if(Auth::user()->hasRole('superadmin'))
                <li>
                    <a href="{{route('roles')}}">Roles & Permissions</a>
                </li>
                @endif
            </ul>
        </div>
    </div>
</div>