routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::group(["middleware" => "auth"],function(){
    Route::resource('posts', 'PostController');
    Route::group(['middleware' => 'can:superadmin'], function () {
        Route::get('roles','RoleController@roles')->name('roles');
        Route::get('change-permissions/{role}','RoleController@changePermission')->name('change-permission');
        Route::put('update-permissions/{role}','RoleController@updatePermission')->name('update-permission');
    });
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    public function tags()
    {
        return $this->hasMany(PostTag::class);
    }

    public static function boot()
    {
        parent::boot();    
        self::deleting(function($post) { // before delete() method call this
            $post->tags()->each(function($tag) {
               $tag->delete(); // <-- direct deletion
            });
            // do the rest of the cleanup...
       });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getRouteKeyName()
    {
        return "slug";
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Builder;

use App\{
    Post,
    PostTag
};
use Image,Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::orderBy('updated_at','desc');
        
        if($request->search){
            $posts->whereHas('tags',function(Builder $query){
                $query->where('tag_name','LIKE','%'.request()->search.'%');
            });
        }

        $posts = $posts->paginate(6);
        return view('posts.list',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::user()->hasPermission('add_post'))
            abort(403,"Unauthorized Action.");

        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!Auth::user()->hasPermission('add_post'))
            abort(403,"Unauthorized Action.");

        $this->validate($request,[
            "title" => "required|max:100",
            "description" => "required|max:1000",
            "image" =>  "required|image|max:1536",
            "tags"   =>  "required|max:200",
        ]);
        
        if($request->hasFile('image')) {
            $filenamewithextension = $request->file('image')->getClientOriginalName();
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
            $extension = $request->file('image')->getClientOriginalExtension();
            $filenametostore = $filename.'_'.time().'.'.$extension;

            //Upload File
            $request->file('image')->storeAs('public/featured_image', $filenametostore);
            $request->file('image')->storeAs('public/featured_image/thumbnail', $filenametostore);
            
            $smallthumbnailpath = public_path('storage/featured_image/thumbnail/'.$filenametostore);
            $this->createThumbnail($smallthumbnailpath, 150, 93);
      
        }

        $post = new Post;
        $post->title = $request->title;
        $post->user_id = Auth::id();
        $post->slug = Str::slug($request->title." ".time(),"-");
        $post->description = $request->description;
        $post->featured_image = $filenametostore;
        $post->save();

        $tags = explode(",",$request->tags);
        $post_tags = [];
        foreach($tags as $tag){
            array_push($post_tags,["post_id" => $post->id,"tag_name" => $tag]);
        }

        PostTag::insert($post_tags);

        return redirect()->route('posts.index')->with('status','Post uploaded successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        if(!Auth::user()->hasPermission('edit_post'))
            abort(403,"Unauthorized Action.");

        $tags = $post->tags()->pluck('tag_name')->toArray();
        return view('posts.edit',compact('post','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Post $post)
    {
        if(!Auth::user()->hasPermission('edit_post'))
            abort(403,"Unauthorized Action.");
        
        $this->validate($request,[
            "title" => "required|max:100",
            "description" => "required|max:1000",
            "image" =>  "nullable|image|max:1536",
            "tags"   =>  "required|max:200",
        ]);
        
        if($request->hasFile('image')) {
            $filenamewithextension = $request->file('image')->getClientOriginalName();
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
            $extension = $request->file('image')->getClientOriginalExtension();
            $filenametostore = $filename.'_'.time().'.'.$extension;

            //Upload File
            $request->file('image')->storeAs('public/featured_image', $filenametostore);
            $request->file('image')->storeAs('public/featured_image/thumbnail', $filenametostore);
            
            $smallthumbnailpath = public_path('storage/featured_image/thumbnail/'.$filenametostore);
            $this->createThumbnail($smallthumbnailpath, 150, 93);
      
        }

        $post->title = $request->title;
        $post->user_id = Auth::id();
        $post->slug = Str::slug($request->title." ".time(),"-");
        $post->description = $request->description;
        if($request->hasfile('image')){
            $post->featured_image = $filenametostore;
        }
        $post->save();

        $post->tags()->delete();
        
        $tags = explode(",",$request->tags);
        $post_tags = [];
        foreach($tags as $tag){
            array_push($post_tags,["post_id" => $post->id,"tag_name" => $tag]);
        }

        PostTag::insert($post_tags);

        return redirect()->route('posts.index')->with('status','Post updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if(!Auth::user()->hasPermission('delete_post'))
            abort(403,"Unauthorized Action.");
        
        $post->delete();

        return redirect()->route('posts.index')->with('status','Post deleted successfully.');
    }

    public function createThumbnail($path, $width, $height)
    {
        $img = Image::make($path)->resize($width, $height, function ($constraint) {
            $constraint->aspectRatio();
        });
        $img->save($path);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">Create New Posts</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if($errors->any())
                    <div class="alert alert-danger" role="alert">
                        <ul>
                        @foreach($errors->all() as $key => $error)
                        <li>{{$error}} </li>        
                        @endforeach
                        </ul>
                    </div>
                    @endif


                    <form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="">Title :</label>
                            <input type="text" class="form-control" name="title" placeholder="Enter Post Title" required>
                        </div>

                        <div class="form-group">
                            <label for="">Description :</label>
                            <textarea name="description" id="" class="form-control" placeholder="Enter Post Description" required></textarea>
                        </div>

                        <div class="form-group">
                            <label for="">Featured Image :</label>
                            <input type="file" name="image" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="">Tags</label>
                            <input type="text" name="tags" class="form-control" required placeholder="Enter Tags">
                            <span style="color:red">For multiple tags please separate tags by ",". For e.g. HTML,PHP</span>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">Edit Post "{{$post->title}}"</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if($errors->any())
                    <div class="alert alert-danger" role="alert">
                        <ul>
                        @foreach($errors->all() as $key => $error)
                        <li>{{$error}} </li>        
                        @endforeach
                        </ul>
                    </div>
                    @endif


                    <form action="{{route('posts.update',$post->slug)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Title :</label>
                            <input type="text" class="form-control" name="title" placeholder="Enter Post Title" required value="{{old("title",$post->title)}}">
                        </div>

                        <div class="form-group">
                            <label for="">Description :</label>
                            <textarea name="description" id="" class="form-control" placeholder="Enter Post Description" required>{{old("description",$post->description)}}</textarea>
                        </div>
                        <br>
                        <span>In case you wan to change featured image:</span>
                        <div class="form-group">
                            <label for="">Featured Image :</label>
                            <input type="file" name="image" class="form-control">
                            <label for="">Current Image</label> &nbsp; &nbsp; <img src="{{asset('storage/featured_image/thumbnail/'.$post->featured_image)}}" alt="" srcset="">
                        </div>

                        <div class="form-group">
                            <label for="">Tags</label>
                            <input type="text" name="tags" class="form-control" required placeholder="Enter Tags" value="{{old('tags',implode(",",$tags))}}">
                            <span style="color:red">For multiple tags please separate tags by ",". For e.g. HTML,PHP</span>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-9">New Post</div>
                        <div class="col-md-3">
                            <form action="{{route('posts.index')}}" method="get">
                                <input type="text" class="form-control" name="search" placeholder="Search by tags">
                            </form>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <th>S.No</th>
                                <th>Thumbnail</th>
                                <th>Title</th>
                                <th>Short Description</th>
                                <th>Tags</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                @forelse($posts as $key => $post)
                                <tr>
                                    <td>{{$posts->firstItem() + $key}}</td>
                                    <td><img src="{{asset('storage/featured_image/thumbnail/'.$post->featured_image)}}" alt="thumbnail"></td>
                                    <td>{{ucfirst($post->title)}}</td>
                                    <td>{{Str::limit($post->description,30)}}..</td>
                                    <td>{{implode(",",$post->tags()->pluck('tag_name')->toArray())}}</td>
                                    <td>{{date('d-M-Y',strtotime($post->created_at))}}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton{{$key}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton{{$key}}">
                                                <a class="dropdown-item" href="{{route('posts.show',$post->slug)}}">Detail</a>
                                                @if(Auth::user()->hasPermission('edit_post'))
                                                <a class="dropdown-item" href="{{route('posts.edit',$post->slug)}}">Edit</a>
                                                @endif
                                                @if(Auth::user()->hasPermission('delete_post'))
                                                <a class="dropdown-item" href="#" onclick="document.getElementById('deletePost{{$key}}').submit()">Delete</a>
                                                <form action="{{route('posts.destroy',$post->slug)}}" id="deletePost{{$key}}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                                @endif
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="6">No new posts found.</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {{$posts->appends(request()->query())->links()}}
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @include('sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">Post Detail of "{{$post->title}}"</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-md-3">
                        <img src="{{asset('storage/featured_image/'.$post->featured_image)}}" alt="thumbnail" style="width:100%">
                        </div>
                        <div class="col-md-9">
                        <h3>{{$post->title}}</h3>
                        <h6>Created By : {{$post->user->name ?? "--"}}</h6>
                        <h6>Created At: {{date('d-M-Y',strtotime($post->created_at))}}</h6>
                        <h6>Tags : {{implode(",",$post->tags()->pluck('tag_name')->toArray())}}</h6>
                        <p>
                            {{$post->description}}
                        </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection